git-sync:
  bin_path: /opt/git-sync/bin/git-sync
  env_files:
  - /opt/git-sync/.env-agent-default
vector:
  bin_path: /opt/vector/bin/vector
  embedded_config_dirs:
  - /etc/vector
  log_path: /var/log/messages
  systemd_unit: vector.service
vector-agent:
  config_root_dir: .
  config_subdir_patterns: []
  configs_workdir: /opt/vector-agent/vector-confdir
  env_files:
    input:
    - /etc/vector/.env
    output: /opt/vector-agent/.env-vector
  reload_timeout_sec: 180
  repo:
    ssh_key_path: null
    ssh_known_hosts_path: null
    url: https://github.com/alexeynl/vector-configs.git
    use_gitsync_settings: true
  root_vrl_path_env_name: VECTOR_CONFIG_PATH
